Management/Controllers/GoodsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Management.Models;
using Management.Models.Goods;

namespace Management.Controllers
{
    public class GoodsController : Controller
    {
        private ManagementDBContext db = new ManagementDBContext();

        // GET: Goods
        public ActionResult Index()
        { 
            if (Session["CurrentUserId"] != null && Session["CurrentUserIsAdminister"] != null)
            {
                return View(db.Goods.ToList());
            }
            else
                return RedirectToAction("Info", "Home", new { Info = "请先登录" });
        }

        // GET: Goods/Details/5
        public ActionResult Details(int? id)
        {
            if (Session["CurrentUserId"] != null && Session["CurrentUserIsAdminister"] != null)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Goods goods = db.Goods.Find(id);
                if (goods == null)
                {
                    return HttpNotFound();
                }
                return View(goods);
            }
            else
                return RedirectToAction("Info", "Home", new { Info = "请先登录" });
        }

        // GET: Goods/Create
        public ActionResult Create()
        {
            if (Session["CurrentUserId"] != null && Session["CurrentUserIsAdminister"] != null)
            {
                if ((bool)Session["CurrentUserIsAdminister"])
                    return View();
                else
                    return RedirectToAction("info", "Home", new { Info = "账号 " + Session["CurrentUserId"] + " 不是管理员" });
            }
            else
                return RedirectToAction("Info", "Home", new { Info = "请先登录" });
        }

        // POST: Goods/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "GoodsName,GoodsNum,GoodsPrice,GoodsType,GoodsBuyTime")] Goods goods)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    goods.GoodsBuyTime = DateTime.Now;
                    db.Goods.Add(goods);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch
            {
                return RedirectToAction("info", "Home", new { Info = "添加出错" });
            }
            return View(goods);
        }

        // GET: Goods/Edit/5
        public ActionResult Edit(int? id)
        {
            if (Session["CurrentUserId"] != null && Session["CurrentUserIsAdminister"] != null)
            {
                if ((bool)Session["CurrentUserIsAdminister"])
                {
                    if (id == null)
                    {
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                    }
                    Goods goods = db.Goods.Find(id);
                    if (goods == null)
                    {
                        return HttpNotFound();
                    }
                    return View(goods);
                }
                else
                    return RedirectToAction("info", "Home", new { Info = "账号 " + Session["CurrentUserId"] + " 不是管理员" });
            }
            else
                return RedirectToAction("Info", "Home", new { Info = "请先登录" });
        }

        // POST: Goods/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "GoodsId,GoodsName,GoodsNum,GoodsPrice,GoodsType,GoodsBuyTime")] Goods goods)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Entry(goods).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View(goods);
            }
            catch
            {
                return RedirectToAction("info", "Home", new { Info = "编辑出错" });
            }
        }

        // GET: Goods/Delete/5
        public ActionResult Delete(int? id)
        {
            if (Session["CurrentUserId"] != null && Session["CurrentUserIsAdminister"] != null)
            {
                if ((bool)Session["CurrentUserIsAdminister"])
                {
                    if (id == null)
                    {
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                    }
                    Goods goods = db.Goods.Find(id);
                    if (goods == null)
                    {
                        return HttpNotFound();
                    }
                    return View(goods);
                }
                else
                    return RedirectToAction("info", "Home", new { Info = "账号 " + Session["CurrentUserId"] + " 不是管理员" });
            }
            else
                return RedirectToAction("Info", "Home", new { Info = "请先登录" });
        }

        // POST: Goods/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Goods goods = db.Goods.Find(id);
            db.Goods.Remove(goods);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Management/Controllers/HomeController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Management.Models;
using Management.Models.Person;

namespace Management.Controllers
{
    public class HomeController : Controller
    {
        private ManagementDBContext db = new ManagementDBContext();

        // GET: Home
        public ActionResult Index()
        {
            //return View();
            return RedirectToAction("Index", "Operation");
        }

        // GET: Home/Info
        public ActionResult Info(string info)
        {
            ViewBag.Info = info;
            return View();
        }

        // GET: Home/Logout
        public ActionResult Logout()
        {
            Session.Clear();
            return RedirectToAction("Index");
        }

        // GET: Home/Login
        public ActionResult Login()
        {
            return View();
        }

        // POST: Home/Login
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login([Bind(Include = "PersonId,Password,Name")] Person person)
        {
            Person userinfo;
            ViewBag.LoginState = false;
            if (int.TryParse(person.Name,out int id))
            {
                person.PersonId = id;
                userinfo = db.Persons.FirstOrDefault(u => u.PersonId == person.PersonId && u.Password == person.Password);
                if (userinfo != null)
                    ViewBag.LoginState = true;
                else
                {
                    userinfo = db.Persons.FirstOrDefault(u => u.Name == person.Name && u.Password == person.Password);
                    if (userinfo != null)
                        ViewBag.LoginState = true;
                }
            }
            else
            {
                userinfo = db.Persons.FirstOrDefault(u => u.Name == person.Name && u.Password == person.Password);
                if(userinfo != null)
                    ViewBag.LoginState = true;
            }
            
            if (ViewBag.LoginState)
            {
                Session["CurrentUserId"] = userinfo.PersonId;
                Session["CurrentUserIsAdminister"] = userinfo.IsAdminister;
                return RedirectToAction("info", new { Info = ((bool)Session["CurrentUserIsAdminister"] ? "管理员 : " : "普通用户 : ")+ Session["CurrentUserId"].ToString() + " 登录成功" });
            }
            else
            {
                return RedirectToAction("info", new { Info = "用户 " + person.Name + " 登录失败" });
            }
            
        }


        // GET: Home/Regester
        public ActionResult Register()
        {
            return View();
        }

        // POST: Home/Register
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Register([Bind(Include = "Password,Name,Phone,Department")] Person person)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    person.IsAdminister = false;
                    db.Persons.Add(person);
                    db.SaveChanges();
                    return RedirectToAction("Info", new { info = ("你注册的账户是: " + person.PersonId) });
                }
                else
                {
                    return RedirectToAction("Info", new { info = "注册失败" });
                }
            }
            catch
            {
                return RedirectToAction("Info", new { info = "用户名已被注册" });
            }
           
        }



        // GET: Home/Edit
        public ActionResult Edit(int? id)
        {
            if (Session["CurrentUserId"] != null && Session["CurrentUserIsAdminister"] != null)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Person person = db.Persons.Find(id);
                if (person == null)
                {
                    return HttpNotFound();
                }
                return View(person);
            }
            else
                return RedirectToAction("Info", "Home", new { Info = "请先登录" });
        }

        /********************************************** 修改IsAdminister **************************************/
        /**************************************** 更新Session[IsAdminister]的状态 **************************************/
        // POST: Home/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PersonId,Password,Name,Phone,Department")] Person person)
        {
            if (ModelState.IsValid)
            {
                db.Entry(person).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(person);
        }


    }
}

Management/Controllers/PeopleController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Management.Models;
using Management.Models.Person;

namespace Management.Controllers
{
    public class PeopleController : Controller
    {
        private ManagementDBContext db = new ManagementDBContext();

        // GET: People
        public ActionResult Index()
        {
            if (Session["CurrentUserId"] != null && Session["CurrentUserIsAdminister"] != null)
                if ((bool)Session["CurrentUserIsAdminister"])
                    return View(db.Persons.ToList());
                else
                    return RedirectToAction("info", "Home", new { Info = "账号 " + Session["CurrentUserId"] + " 不是管理员" });
            else
                return RedirectToAction("Info", "Home", new { Info = "请先登录" });
            
        }
    
        // GET: People/Details/5
        public ActionResult Details(int? id)
        {
            if (Session["CurrentUserId"] != null && Session["CurrentUserIsAdminister"] != null)
            {
                if ((bool)Session["CurrentUserIsAdminister"])
                {
                    if (id == null)
                    {
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                    }
                    Person person = db.Persons.Find(id);
                    if (person == null)
                    {
                        return HttpNotFound();
                    }
                    return View(person);
                }
                else
                    return RedirectToAction("info", "Home", new { Info = "账号 " + Session["CurrentUserId"] + " 不是管理员" });
            }
            else
                return RedirectToAction("Info", "Home", new { Info = "请先登录" });
        }

/********************************************** 调试用版本 **************************************/
/*      
            // GET: People/Create
        public ActionResult Create()
        {
            return View();
        }
*/
        // GET: People/Create
        public ActionResult Create()
        {
            if (Session["CurrentUserId"] != null && Session["CurrentUserIsAdminister"] != null)
            {
                if ((bool)Session["CurrentUserIsAdminister"])
                    return View();
                else
                    return RedirectToAction("info", "Home", new { Info = "账号 " + Session["CurrentUserId"] + " 不是管理员" });
            }
            else
                return RedirectToAction("Info", "Home", new { Info = "请先登录" });
        }


        // POST: People/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PersonId,Password,Name,Phone,Department,IsAdminister")] Person person)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Persons.Add(person);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View(person);
            }
            catch
            {
                return RedirectToAction("Info", "Home", new { Info = "用户名已被注册" });
            }
            
        }

        // GET: People/Edit/5
        public ActionResult Edit(int? id)
        {
            if (Session["CurrentUserId"] != null && Session["CurrentUserIsAdminister"] != null)
            {
                if ((bool)Session["CurrentUserIsAdminister"])
                {
                    if (id == null)
                    {
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                    }
                    Person person = db.Persons.Find(id);
                    if (person == null)
                    {
                        return HttpNotFound();
                    }
                    return View(person);
                }
                else
                    return RedirectToAction("info", "Home", new { Info = "账号 " + Session["CurrentUserId"] + " 不是管理员" });
            }
            else
                return RedirectToAction("Info", "Home", new { Info = "请先登录" });
        }

/********************************************** 修改IsAdminister **************************************/
/**************************************** 更新Session[IsAdminister]的状态 **************************************/
        // POST: People/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PersonId,Password,Name,Phone,Department,IsAdminister")] Person person)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Entry(person).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View(person);
            }
            catch
            {
                return RedirectToAction("Info", "Home", new { Info = "用户名已存在" });
            }
            
        }

        // GET: People/Delete/5
        public ActionResult Delete(int? id)
        {
            if (Session["CurrentUserId"] != null && Session["CurrentUserIsAdminister"] != null)
            {
                if ((bool)Session["CurrentUserIsAdminister"])
                {
                    if (id == null)
                    {
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                    }
                    Person person = db.Persons.Find(id);
                    if (person == null)
                    {
                        return HttpNotFound();
                    }
                    return View(person);
                }
                else
                    return RedirectToAction("info", "Home", new { Info = "账号 " + Session["CurrentUserId"] + " 不是管理员" });
            }
            else
                return RedirectToAction("Info", "Home", new { Info = "请先登录" });
        }

/**************************************** 更改自己账户bug **************************************/
        // POST: People/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Person person = db.Persons.Find(id);
            db.Persons.Remove(person);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Management/Views/Home/Edit.cshtml
@model Management.Models.Person.Person

@{
    ViewBag.Title = "编辑个人信息";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 style="text-align:center;margin-bottom:70px">编辑个人信息</h2>

<hr />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <h4 style="text-align:center">个人信息</h4>
    <div class="form-horizontal" style="padding-left:300px">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.PersonId)

        <div class="form-group">
            @Html.LabelFor(model => model.PersonId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.PersonId)
                @Html.ValidationMessageFor(model => model.PersonId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10" position:relative;>
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Department, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Department, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Department, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsAdminister, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.IsAdminister)
                @Html.ValidationMessageFor(model => model.IsAdminister, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="保存" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<hr />
<div style="text-align:center">
    <button type="button" class="btn btn-outline-primary">@Html.ActionLink("返回主页", "Index")</button>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Management/Views/Home/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@{
    ViewBag.Title = "主页";
}

<h2 style="text-align:center;margin-bottom:70px">主页</h2>

<hr />
<p>
    @Html.ActionLink("账户列表", "Index", "People")|
    @Html.ActionLink("商品列表", "Index", "Goods")
</p>

Management/Views/Home/Login.cshtml
@model Management.Models.Person.Person
@{
    ViewBag.Title = "登录";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 style="text-align:center;margin-bottom:70px">登录</h2>

<hr />
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal" style="padding-left:300px">
        <h4 style="padding-left:240px">账户</h4>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10" position:relative;>
                <input id="pwd_lookOrNot" type="password" name="Password" value="" class="form-control" />
                <span id="look_orNot" class="glyphicon glyphicon-eye-open"></span>
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10" style="padding-left:107px">
                <input type="submit" value="登录" class="btn btn-default" />
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Management/Views/Home/Register.cshtml
@model Management.Models.Person.Person

@{
    ViewBag.Title = "注册";
}

<h2 style="text-align:center;margin-bottom:70px">注册</h2>

<hr />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal" style="padding-left:300px">
        <h4 style="padding-left:240px">账户</h4>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input id="pwd_lookOrNot" type="password" name="Password" value="" class="form-control" />
                <span id="look_orNot" class="glyphicon glyphicon-eye-open"></span>
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Department, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Department, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Department, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10" style="padding-left:103px">
                <input name="Button" type="submit" value="注册" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<p style="text-align:right">
    @Html.ActionLink("返回主页", "Index")
</p>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Management/Views/Home/info.cshtml
@{
    ViewBag.Title = "提示";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 style="margin-bottom:70px">提示</h2>

<hr />

<h4 style="text-align:center;margin-top:30px">
    @ViewBag.Info
</h4>


<hr />
<p style="text-align:center">
    <button type="button" class="btn btn-outline-primary">@Html.ActionLink("返回主页", "Index")</button>
    <button type="button" class="btn btn-outline-primary">@Html.ActionLink("去登录", "Login")</button>
</p>